### ISSUE TITLE
Auto check app and update at boot time

### ISSUE THREAD

**Issue by DrSensor** [WebReflection/benja#50]
First of all, thank you for this really kind OS and Happy New Year :tada:.

Accidentally found this project on my trip :smile: and really like how you choose Arch Linux as the main OS for broader support of ARM variant board. I realize this OS is suitable for my next project because I can develop SPA and deploy it directly to the board (though need to build template project with webpack support first). 

However, I realize there are features that I need to make the development more like App centric (something like publishing and updating Android App). I want to make it more like Android TV that will update the app automatically at boot time. (Android TV also updates the OS and firmware at boot time but I don't need that for a moment) 

There are some ways that cross my mind to implement that:
1. Check and compare `package.json` with the __npm registry__ (if my memory is correct there is lib for that). This scenario requires deploying my app as _npm package_ then publish it to __npm registry__ (private or public).
2. Use Hot Deployment as in [Ionic](https://ionicframework.com/docs/pro/deploy/) does (still don't know how it works)
3. Make electron based project, build and deploy as [`snap`](https://snapcraft.io/) package. However, it needs to install `snapd` on the SBC. Also, [electron](https://electronjs.org/docs/tutorial/supported-platforms) and [elentron-builder](https://github.com/electron-userland/electron-builder#programmatic-usage) only support ARM v7 with hard-float ABI and NEON. 

Some good candidates (still surveying) for FOTA updates: https://mender.io/

Any other recommendation for doing publishing-updating app?

> PS: I think benja OS is good alternative to [Android Things](https://developer.android.com/things/index.html) for Web App Developer

> when you have time, maybe you want to tinker with [nanopi](http://www.nanopi.org/)

**Comment by WebReflection** [comment]
sorry to come back this late. this project provides the bare minimum to start, you can configure it after all as you prefer, create your own ISO from your SD Card, and distribute that instead.

I have received way too few donations to keep supporting this project so I won't waste too much time on it until I have more time or interest myself in improving.

Since other players started "playing" too I also would like to see if there's the possibility to simply use those projects from big companies with many developers paid to do what here I am actually losing (in terms of money, the ISO files have a cost to be downloadable like that)

Closing as there's no intent in improving much the current project.
